/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CaixaController;
import Model.Pedidos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author W
 */
public class Caixa extends javax.swing.JFrame {

    private final CaixaController controller;
    //crio uma field fora do meu metodo para que todos metodos possam acessar o controller


    /**
     * Creates new form telaSalao
     */
    public Caixa(){
        initComponents();
        //apresento o meu controller a view
        controller = new CaixaController(this);
        try {
            //inicio o metodo que atualiza a tabela
            iniciar();
        } catch (SQLException ex) {
            Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaBanco = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbl_observacoes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        botao_salvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        concluido = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        lbl_pedido = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl_valor = new javax.swing.JTextField();
        lbl_data = new javax.swing.JTextField();
        lbl_hora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_imagem_painelfundo = new javax.swing.JLabel();
        lbl_imagemsalao = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelaBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id:", "Pedidos:", "Valor:", "Data:", "Hora", "Observação:", "Concluído:"
            }
        ));
        jScrollPane1.setViewportView(TabelaBanco);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 621, 1110, 320));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pedidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        lbl_observacoes.setColumns(20);
        lbl_observacoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_observacoes.setRows(5);
        jScrollPane2.setViewportView(lbl_observacoes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 310, 160));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CAIXA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, -1, -1));

        botao_salvar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botao_salvar.setText("Salvar");
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 310, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, 310, 40));
        getContentPane().add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 100, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Observações:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        concluido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        concluido.setForeground(new java.awt.Color(255, 255, 255));
        concluido.setText("Concluido");
        getContentPane().add(concluido, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 180, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Atualizar Tabela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 230, 30));

        lbl_pedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_pedidoActionPerformed(evt);
            }
        });
        getContentPane().add(lbl_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 200, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 200, -1));

        lbl_valor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lbl_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 200, -1));

        lbl_data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lbl_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 200, -1));

        lbl_hora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(lbl_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 200, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Hora:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor R$:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Funcionário:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 20));

        lbl_imagem_painelfundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\Agenda-PainelFundo.png")); // NOI18N
        getContentPane().add(lbl_imagem_painelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 1330, -1));

        lbl_imagemsalao.setBackground(new java.awt.Color(255, 255, 255));
        lbl_imagemsalao.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\menusalao.jpg")); // NOI18N
        lbl_imagemsalao.setToolTipText("");
        getContentPane().add(lbl_imagemsalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jCheckBox2.setText("jCheckBox2");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_pedidoActionPerformed

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
       String pedido = getLbl_pedido().getText();
        int valor = Integer.parseInt((getLbl_valor().getText()));
       String data = getLbl_data().getText();
       String hora = getLbl_hora().getText();
       String observacao = getLbl_observacoes().getText();
       boolean concluido = false;
       
       Pedidos pedidos = new Pedidos(pedido, valor, data, hora, observacao, concluido);
        try {
            controller.insert(pedidos);
        } catch (SQLException ex) {
            Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_botao_salvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.controller.alterarpedido();
        } catch (SQLException ex) {
            Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            this.controller.atualizaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Caixa().setVisible(true);
  
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaBanco;
    private javax.swing.JButton botao_salvar;
    private javax.swing.JCheckBox concluido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lbl_data;
    private javax.swing.JTextField lbl_hora;
    private javax.swing.JLabel lbl_imagem_painelfundo;
    private javax.swing.JLabel lbl_imagemsalao;
    private javax.swing.JTextArea lbl_observacoes;
    private javax.swing.JTextField lbl_pedido;
    private javax.swing.JTextField lbl_valor;
    private javax.swing.JTextField tfid;
    // End of variables declaration//GEN-END:variables

    public boolean isconcluido(){
        boolean concluido = false;
        if(getConcluido().isSelected()){
            concluido = true;
        }
        return concluido;
    }
    
    
    //eis a chamada do meu metodo que atualiza a tabela
    private void iniciar() throws SQLException {
       controller.atualizaTabela();

    }

    public JTextField getTfid() {
        return tfid;
    }

    public void setTfid(JTextField tfid) {
        this.tfid = tfid;
    }

    public JCheckBox getConcluido() {
        return concluido;
    }

    public void setConcluido(JCheckBox concluido) {
        this.concluido = concluido;
    }
    

    public JTable getTabelaBanco() {
        return TabelaBanco;
    }

    public void setTabelaBanco(JTable TabelaBanco) {
        this.TabelaBanco = TabelaBanco;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JButton getBotao_salvar() {
        return botao_salvar;
    }

    public void setBotao_salvar(JButton botao_salvar) {
        this.botao_salvar = botao_salvar;
    }

    public JTextField getLbl_data() {
        return lbl_data;
    }

    public void setLbl_data(JTextField lbl_data) {
        this.lbl_data = lbl_data;
    }

    public JTextField getLbl_hora() {
        return lbl_hora;
    }

    public void setLbl_hora(JTextField lbl_hora) {
        this.lbl_hora = lbl_hora;
    }

    public JTextArea getLbl_observacoes() {
        return lbl_observacoes;
    }

    public void setLbl_observacoes(JTextArea lbl_observacoes) {
        this.lbl_observacoes = lbl_observacoes;
    }

    public JTextField getLbl_pedido() {
        return lbl_pedido;
    }

    public void setLbl_pedido(JTextField lbl_pedido) {
        this.lbl_pedido = lbl_pedido;
    }

    public JTextField getLbl_valor() {
        return lbl_valor;
    }

    public void setLbl_valor(JTextField lbl_valor) {
        this.lbl_valor = lbl_valor;
    }

    
}
