/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.MenuPrincipal;
import Controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author W
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        controller = new LoginController(this);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_entrar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        tf_nome = new javax.swing.JTextField();
        pf_senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lbl_nome_usuario = new javax.swing.JLabel();
        lbl_nome_login1 = new javax.swing.JLabel();
        lbl_nome_login = new javax.swing.JLabel();
        lbl_painel_login = new javax.swing.JLabel();
        lbl_imagem_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_entrar.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        btn_entrar.setText("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 230, -1));

        btn_cadastrar.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, 230, -1));

        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 320, 30));

        pf_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(pf_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 320, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Não tem uma conta ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 140, -1));

        lbl_nome_usuario.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lbl_nome_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome_usuario.setText("Usuário:");
        getContentPane().add(lbl_nome_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 30));

        lbl_nome_login1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lbl_nome_login1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome_login1.setText("Senha:");
        getContentPane().add(lbl_nome_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 100, 40));

        lbl_nome_login.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lbl_nome_login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nome_login.setText("Login");
        getContentPane().add(lbl_nome_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 110, 40));

        lbl_painel_login.setForeground(new java.awt.Color(255, 102, 0));
        lbl_painel_login.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Documents\\NetBeansProjects\\AltamiraFood\\src\\main\\java\\View\\imagens\\painel-login.png")); // NOI18N
        lbl_painel_login.setText("jLabel1");
        lbl_painel_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbl_painel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 540, -1));

        lbl_imagem_login.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\tela_login3.png")); // NOI18N
        getContentPane().add(lbl_imagem_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void pf_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_senhaActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
       TelaCadastro telaCadastro = new TelaCadastro();
       telaCadastro.setVisible(true);
    
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed

        try {
            controller.autenticar();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_imagem_login;
    private javax.swing.JLabel lbl_nome_login;
    private javax.swing.JLabel lbl_nome_login1;
    private javax.swing.JLabel lbl_nome_usuario;
    private javax.swing.JLabel lbl_painel_login;
    private javax.swing.JPasswordField pf_senha;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public JPasswordField getPf_senha() {
        return pf_senha;
    }

    public void setPf_senha(JPasswordField pf_senha) {
        this.pf_senha = pf_senha;
    }

    public JTextField getTf_nome() {
        return tf_nome;
    }

    public void setTf_nome(JTextField tf_nome) {
        this.tf_nome = tf_nome;
    }

    
    
    
}
