/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.MenuPrincipalController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author W
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_imagem_menuprincipal = new javax.swing.JLabel();
        mb_menuprincipal = new javax.swing.JMenuBar();
        jm_cadastro = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jm_operacao = new javax.swing.JMenu();
        Menucardapio = new javax.swing.JMenuItem();
        MenuCaixa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_imagem_menuprincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Documents\\NetBeansProjects\\AltamiraFood\\src\\main\\java\\View\\imagens\\253-2538454_de-restaurante-1920-x-1080.jpg")); // NOI18N

        jm_cadastro.setText("Cadastro");
        jm_cadastro.setToolTipText("");
        jm_cadastro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\icons\\funcionarioicone.png")); // NOI18N
        jMenuItem2.setText("Funcionário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jm_cadastro.add(jMenuItem2);

        mb_menuprincipal.add(jm_cadastro);

        jm_operacao.setText("Operação");
        jm_operacao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Menucardapio.setBackground(new java.awt.Color(255, 255, 255));
        Menucardapio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Menucardapio.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\icone_cardapio.png")); // NOI18N
        Menucardapio.setText("Cardápio");
        Menucardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenucardapioActionPerformed(evt);
            }
        });
        jm_operacao.add(Menucardapio);

        MenuCaixa.setBackground(new java.awt.Color(255, 255, 255));
        MenuCaixa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MenuCaixa.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\icone_caixa2.png")); // NOI18N
        MenuCaixa.setText("Caixa");
        MenuCaixa.setToolTipText("");
        MenuCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCaixaActionPerformed(evt);
            }
        });
        jm_operacao.add(MenuCaixa);

        jMenuItem1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\outline_restaurant_menu_black_24dp.png")); // NOI18N
        jMenuItem1.setText("Cozinha");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_operacao.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\icons\\agenda-icon.png")); // NOI18N
        jMenuItem4.setText("BD Funcionários");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jm_operacao.add(jMenuItem4);

        mb_menuprincipal.add(jm_operacao);

        setJMenuBar(mb_menuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_imagem_menuprincipal)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_imagem_menuprincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCaixaActionPerformed
        this.controller.navegarParaOCaixa();
    }//GEN-LAST:event_MenuCaixaActionPerformed

    private void MenucardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenucardapioActionPerformed
         this.controller.navegarParaTelaCardapio();
    }//GEN-LAST:event_MenucardapioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            this.controller.navegarParaCozinha();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.controller.navegarParaCadastro();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            this.controller.navegarParaBDfuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCaixa;
    private javax.swing.JMenuItem Menucardapio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jm_cadastro;
    private javax.swing.JMenu jm_operacao;
    private javax.swing.JLabel lbl_imagem_menuprincipal;
    private javax.swing.JMenuBar mb_menuprincipal;
    // End of variables declaration//GEN-END:variables
}
