/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.TelaCozinhaController;
import Model.DAO.CozinhaDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author W
 */
public class TelaCozinha extends javax.swing.JFrame {
    
    private final TelaCozinhaController controller;
    /**
     * Creates new form TelaCozinha
     */
    public TelaCozinha() throws SQLException {
        initComponents();
        controller = new TelaCozinhaController(this);
        this.controller.mostrapedidos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        tfhora3 = new javax.swing.JTextField();
        tfid1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfpedido5 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfobservacoes1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        botaopedido2 = new javax.swing.JButton();
        botaopedido5 = new javax.swing.JButton();
        botaopedido4 = new javax.swing.JButton();
        botaopedido3 = new javax.swing.JButton();
        botaopedido6 = new javax.swing.JButton();
        botaopedido1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfobservacoes2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfobservacoes6 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tfobservacoes3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tfobservacoes5 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        tfobservacoes4 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tfpedido1 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        tfpedido4 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        tfpedido3 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        tfpedido6 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        tfpedido2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        tfid3 = new javax.swing.JTextField();
        tfid4 = new javax.swing.JTextField();
        tfid5 = new javax.swing.JTextField();
        tfid6 = new javax.swing.JTextField();
        tfid2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfhora2 = new javax.swing.JTextField();
        tfhora4 = new javax.swing.JTextField();
        tfhora5 = new javax.swing.JTextField();
        tfhora6 = new javax.swing.JTextField();
        tfhora1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\painel-login.png")); // NOI18N
        jLabel9.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfhora3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfhora3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhora3ActionPerformed(evt);
            }
        });
        getContentPane().add(tfhora3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 90, 110, 30));

        tfid1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfid1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 70, 30));

        tfpedido5.setColumns(20);
        tfpedido5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpedido5.setRows(5);
        jScrollPane1.setViewportView(tfpedido5);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 710, 370, 110));

        tfobservacoes1.setColumns(20);
        tfobservacoes1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfobservacoes1.setRows(5);
        jScrollPane2.setViewportView(tfobservacoes1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 370, 80));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        botaopedido2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaopedido2.setForeground(new java.awt.Color(51, 255, 0));
        botaopedido2.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\outline_done_outline_black_24dp.png")); // NOI18N
        botaopedido2.setText("Pedido Concluído:");
        botaopedido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopedido2ActionPerformed(evt);
            }
        });
        getContentPane().add(botaopedido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 370, 50));

        botaopedido5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaopedido5.setForeground(new java.awt.Color(51, 255, 0));
        botaopedido5.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\outline_done_outline_black_24dp.png")); // NOI18N
        botaopedido5.setText("Pedido Concluído:");
        botaopedido5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopedido5ActionPerformed(evt);
            }
        });
        getContentPane().add(botaopedido5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 960, 370, 50));

        botaopedido4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaopedido4.setForeground(new java.awt.Color(51, 255, 0));
        botaopedido4.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\outline_done_outline_black_24dp.png")); // NOI18N
        botaopedido4.setText("Pedido Concluído:");
        botaopedido4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopedido4ActionPerformed(evt);
            }
        });
        getContentPane().add(botaopedido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 970, 370, 50));

        botaopedido3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaopedido3.setForeground(new java.awt.Color(51, 255, 0));
        botaopedido3.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\outline_done_outline_black_24dp.png")); // NOI18N
        botaopedido3.setText("Pedido Concluído:");
        botaopedido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopedido3ActionPerformed(evt);
            }
        });
        getContentPane().add(botaopedido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 430, 370, 50));

        botaopedido6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaopedido6.setForeground(new java.awt.Color(51, 255, 0));
        botaopedido6.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\outline_done_outline_black_24dp.png")); // NOI18N
        botaopedido6.setText("Pedido Concluído:");
        botaopedido6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopedido6ActionPerformed(evt);
            }
        });
        getContentPane().add(botaopedido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 950, 370, 50));

        botaopedido1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botaopedido1.setForeground(new java.awt.Color(51, 255, 0));
        botaopedido1.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\outline_done_outline_black_24dp.png")); // NOI18N
        botaopedido1.setText("Pedido Concluído:");
        botaopedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopedido1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaopedido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 370, 50));

        tfobservacoes2.setColumns(20);
        tfobservacoes2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfobservacoes2.setRows(5);
        jScrollPane3.setViewportView(tfobservacoes2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 370, 80));

        tfobservacoes6.setColumns(20);
        tfobservacoes6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfobservacoes6.setRows(5);
        jScrollPane4.setViewportView(tfobservacoes6);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 850, 370, 80));

        tfobservacoes3.setColumns(20);
        tfobservacoes3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfobservacoes3.setRows(5);
        jScrollPane5.setViewportView(tfobservacoes3);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 340, 370, 80));

        tfobservacoes5.setColumns(20);
        tfobservacoes5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfobservacoes5.setRows(5);
        jScrollPane6.setViewportView(tfobservacoes5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 850, 370, 80));

        tfobservacoes4.setColumns(20);
        tfobservacoes4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfobservacoes4.setRows(5);
        jScrollPane7.setViewportView(tfobservacoes4);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 860, 370, 80));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Observações:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 820, -1, -1));

        tfpedido1.setColumns(20);
        tfpedido1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpedido1.setRows(5);
        jScrollPane8.setViewportView(tfpedido1);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 370, 110));

        tfpedido4.setColumns(20);
        tfpedido4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpedido4.setRows(5);
        jScrollPane9.setViewportView(tfpedido4);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 720, 370, 110));

        tfpedido3.setColumns(20);
        tfpedido3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpedido3.setRows(5);
        jScrollPane10.setViewportView(tfpedido3);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 180, 370, 110));

        tfpedido6.setColumns(20);
        tfpedido6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpedido6.setRows(5);
        jScrollPane11.setViewportView(tfpedido6);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 710, 370, 110));

        tfpedido2.setColumns(20);
        tfpedido2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfpedido2.setRows(5);
        jScrollPane12.setViewportView(tfpedido2);

        getContentPane().add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 370, 110));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, -1));

        tfid3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfid3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfid3ActionPerformed(evt);
            }
        });
        getContentPane().add(tfid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 90, 70, 30));

        tfid4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfid4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfid4ActionPerformed(evt);
            }
        });
        getContentPane().add(tfid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 70, 30));

        tfid5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfid5ActionPerformed(evt);
            }
        });
        getContentPane().add(tfid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 70, 30));

        tfid6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfid6ActionPerformed(evt);
            }
        });
        getContentPane().add(tfid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 610, 70, 30));

        tfid2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfid2ActionPerformed(evt);
            }
        });
        getContentPane().add(tfid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 70, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Pedido:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 150, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Hora:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 90, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Hora:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, -1, -1));

        tfhora2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfhora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhora2ActionPerformed(evt);
            }
        });
        getContentPane().add(tfhora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 110, 30));

        tfhora4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfhora4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhora4ActionPerformed(evt);
            }
        });
        getContentPane().add(tfhora4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 110, 30));

        tfhora5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfhora5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhora5ActionPerformed(evt);
            }
        });
        getContentPane().add(tfhora5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 610, 110, 30));

        tfhora6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfhora6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhora6ActionPerformed(evt);
            }
        });
        getContentPane().add(tfhora6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 610, 110, 30));

        tfhora1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfhora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhora1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfhora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 110, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Hora:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Hora:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 610, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Hora:");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Pedido:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 680, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Pedido:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 680, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Pedido:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Pedido:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Observações:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 310, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Observações:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 820, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Observações:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 830, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Observações:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\painel-login.png")); // NOI18N
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ID:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 610, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\painel-login.png")); // NOI18N
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\painel-login.png")); // NOI18N
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\painel-login.png")); // NOI18N
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 40, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\painel-login.png")); // NOI18N
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 550, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Observações:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pedido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\imagens\\painel-login.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\W\\Desktop\\View\\menusalao.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaopedido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopedido2ActionPerformed
        try {
            this.controller.mostrapedidos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.controller.concluipedido2();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaopedido2ActionPerformed

    private void tfhora3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhora3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhora3ActionPerformed

    private void tfid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfid1ActionPerformed

    private void botaopedido5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopedido5ActionPerformed
         try {
            this.controller.mostrapedidos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.controller.concluipedido5();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaopedido5ActionPerformed

    private void botaopedido4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopedido4ActionPerformed
         try {
            this.controller.mostrapedidos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.controller.concluipedido4();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaopedido4ActionPerformed

    private void botaopedido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopedido3ActionPerformed
         try {
            this.controller.mostrapedidos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.controller.concluipedido3();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaopedido3ActionPerformed

    private void botaopedido6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopedido6ActionPerformed
         try {
            this.controller.mostrapedidos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.controller.concluipedido6();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaopedido6ActionPerformed

    private void botaopedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopedido1ActionPerformed
        try {
            this.controller.mostrapedidos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            this.controller.concluipedido1();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaopedido1ActionPerformed

    private void tfid3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfid3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfid3ActionPerformed

    private void tfid4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfid4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfid4ActionPerformed

    private void tfid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfid5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfid5ActionPerformed

    private void tfid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfid6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfid6ActionPerformed

    private void tfid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfid2ActionPerformed

    private void tfhora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhora2ActionPerformed

    private void tfhora4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhora4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhora4ActionPerformed

    private void tfhora5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhora5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhora5ActionPerformed

    private void tfhora6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhora6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhora6ActionPerformed

    private void tfhora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhora1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCozinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaCozinha().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaCozinha.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

 


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaopedido1;
    private javax.swing.JButton botaopedido2;
    private javax.swing.JButton botaopedido3;
    private javax.swing.JButton botaopedido4;
    private javax.swing.JButton botaopedido5;
    private javax.swing.JButton botaopedido6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField tfhora1;
    private javax.swing.JTextField tfhora2;
    private javax.swing.JTextField tfhora3;
    private javax.swing.JTextField tfhora4;
    private javax.swing.JTextField tfhora5;
    private javax.swing.JTextField tfhora6;
    private javax.swing.JTextField tfid1;
    private javax.swing.JTextField tfid2;
    private javax.swing.JTextField tfid3;
    private javax.swing.JTextField tfid4;
    private javax.swing.JTextField tfid5;
    private javax.swing.JTextField tfid6;
    private javax.swing.JTextArea tfobservacoes1;
    private javax.swing.JTextArea tfobservacoes2;
    private javax.swing.JTextArea tfobservacoes3;
    private javax.swing.JTextArea tfobservacoes4;
    private javax.swing.JTextArea tfobservacoes5;
    private javax.swing.JTextArea tfobservacoes6;
    private javax.swing.JTextArea tfpedido1;
    private javax.swing.JTextArea tfpedido2;
    private javax.swing.JTextArea tfpedido3;
    private javax.swing.JTextArea tfpedido4;
    private javax.swing.JTextArea tfpedido5;
    private javax.swing.JTextArea tfpedido6;
    // End of variables declaration//GEN-END:variables

    public JTextField getTfhora1() {
        return tfhora1;
    }

    public void setTfhora1(JTextField tfhora1) {
        this.tfhora1 = tfhora1;
    }

    public JTextField getTfhora2() {
        return tfhora2;
    }

    public void setTfhora2(JTextField tfhora2) {
        this.tfhora2 = tfhora2;
    }

    public JTextField getTfhora3() {
        return tfhora3;
    }

    public void setTfhora3(JTextField tfhora3) {
        this.tfhora3 = tfhora3;
    }

    public JTextField getTfhora4() {
        return tfhora4;
    }

    public void setTfhora4(JTextField tfhora4) {
        this.tfhora4 = tfhora4;
    }

    public JTextField getTfhora5() {
        return tfhora5;
    }

    public void setTfhora5(JTextField tfhora5) {
        this.tfhora5 = tfhora5;
    }

    public JTextField getTfhora6() {
        return tfhora6;
    }

    public void setTfhora6(JTextField tfhora6) {
        this.tfhora6 = tfhora6;
    }

    public JTextField getTfid1() {
        return tfid1;
    }

    public void setTfid1(JTextField tfid1) {
        this.tfid1 = tfid1;
    }

    public JTextField getTfid2() {
        return tfid2;
    }

    public void setTfid2(JTextField tfid2) {
        this.tfid2 = tfid2;
    }

    public JTextField getTfid3() {
        return tfid3;
    }

    public void setTfid3(JTextField tfid3) {
        this.tfid3 = tfid3;
    }

    public JTextField getTfid4() {
        return tfid4;
    }

    public void setTfid4(JTextField tfid4) {
        this.tfid4 = tfid4;
    }

    public JTextField getTfid5() {
        return tfid5;
    }

    public void setTfid5(JTextField tfid5) {
        this.tfid5 = tfid5;
    }

    public JTextField getTfid6() {
        return tfid6;
    }

    public void setTfid6(JTextField tfid6) {
        this.tfid6 = tfid6;
    }

    public JTextArea getTfobservacoes1() {
        return tfobservacoes1;
    }

    public void setTfobservacoes1(JTextArea tfobservacoes1) {
        this.tfobservacoes1 = tfobservacoes1;
    }

    public JTextArea getTfobservacoes2() {
        return tfobservacoes2;
    }

    public void setTfobservacoes2(JTextArea tfobservacoes2) {
        this.tfobservacoes2 = tfobservacoes2;
    }

    public JTextArea getTfobservacoes3() {
        return tfobservacoes3;
    }

    public void setTfobservacoes3(JTextArea tfobservacoes3) {
        this.tfobservacoes3 = tfobservacoes3;
    }

    public JTextArea getTfobservacoes4() {
        return tfobservacoes4;
    }

    public void setTfobservacoes4(JTextArea tfobservacoes4) {
        this.tfobservacoes4 = tfobservacoes4;
    }

    public JTextArea getTfobservacoes5() {
        return tfobservacoes5;
    }

    public void setTfobservacoes5(JTextArea tfobservacoes5) {
        this.tfobservacoes5 = tfobservacoes5;
    }

    public JTextArea getTfobservacoes6() {
        return tfobservacoes6;
    }

    public void setTfobservacoes6(JTextArea tfobservacoes6) {
        this.tfobservacoes6 = tfobservacoes6;
    }

    public JTextArea getTfpedido1() {
        return tfpedido1;
    }

    public void setTfpedido1(JTextArea tfpedido1) {
        this.tfpedido1 = tfpedido1;
    }

    public JTextArea getTfpedido2() {
        return tfpedido2;
    }

    public void setTfpedido2(JTextArea tfpedido2) {
        this.tfpedido2 = tfpedido2;
    }

    public JTextArea getTfpedido3() {
        return tfpedido3;
    }

    public void setTfpedido3(JTextArea tfpedido3) {
        this.tfpedido3 = tfpedido3;
    }

    public JTextArea getTfpedido4() {
        return tfpedido4;
    }

    public void setTfpedido4(JTextArea tfpedido4) {
        this.tfpedido4 = tfpedido4;
    }

    public JTextArea getTfpedido5() {
        return tfpedido5;
    }

    public void setTfpedido5(JTextArea tfpedido5) {
        this.tfpedido5 = tfpedido5;
    }

    public JTextArea getTfpedido6() {
        return tfpedido6;
    }

    public void setTfpedido6(JTextArea tfpedido6) {
        this.tfpedido6 = tfpedido6;
    }

 
}
