/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.TelaCardapioController;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author W
 */
public class TelaCardapio extends javax.swing.JFrame {

    private final TelaCardapioController controller;

   



    /**
     * Creates new form telacardapio
     */
    public TelaCardapio() {
        initComponents();
        controller = new TelaCardapioController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        Guarana = new javax.swing.JSpinner();
        selecaoCDS = new javax.swing.JSpinner();
        selecaoPF = new javax.swing.JSpinner();
        selecaoBA = new javax.swing.JSpinner();
        selecaoBF = new javax.swing.JSpinner();
        selecaoBP = new javax.swing.JSpinner();
        selecaoCP = new javax.swing.JSpinner();
        selecaoFG = new javax.swing.JSpinner();
        selecaoCMB = new javax.swing.JSpinner();
        CocaCola = new javax.swing.JSpinner();
        Fanta = new javax.swing.JSpinner();
        selecaoP = new javax.swing.JSpinner();
        btnenviar = new javax.swing.JButton();
        tfvalor = new javax.swing.JTextField();
        tfobservacoes = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Guarana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 40, 30));
        getContentPane().add(selecaoCDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 40, 30));
        getContentPane().add(selecaoPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 40, 30));
        getContentPane().add(selecaoBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 40, 30));
        getContentPane().add(selecaoBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 40, 30));
        getContentPane().add(selecaoBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 40, 30));
        getContentPane().add(selecaoCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, 40, 30));
        getContentPane().add(selecaoFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 40, 30));
        getContentPane().add(selecaoCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 40, 30));
        getContentPane().add(CocaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 40, 30));
        getContentPane().add(Fanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, 40, 30));

        selecaoP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(selecaoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 40, 30));

        btnenviar.setBackground(new java.awt.Color(255, 204, 204));
        btnenviar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnenviar.setText("Fazer Pedido");
        btnenviar.setBorder(new javax.swing.border.MatteBorder(null));
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 200, 40));

        tfvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvalorActionPerformed(evt);
            }
        });
        getContentPane().add(tfvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 130, 30));

        tfobservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfobservacoesActionPerformed(evt);
            }
        });
        getContentPane().add(tfobservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 270, 90));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 153));
        jLabel15.setText("VALOR TOTAL");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 120, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("OBSERVAÇÕES");
        jLabel14.setToolTipText("");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Guaraná 2 Litros........R$11,00");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 360, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fanta laranja 1.5Litros.......R$9,00");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 390, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Picanha.............................R$45,00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 400, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Camarão ao Molho Branco..R$40,00");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 410, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Frango Guisado.................R$15,00");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 400, 50));

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Coca-Cola em lata..............R$6,00");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 380, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Costela de Porco...............R$25,00 ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 400, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peixe Frito.........................R$25,00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 400, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Carne de Sol......................R$18,00");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 400, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bisteca de Porco...............R$20,00");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 400, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bife de Fígado...................R$12,00");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 390, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bife Acebolado..................R$15,00");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 400, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/painel .png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nova view restaurante.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        controller.salvaPedido();
        getTfvalor().setText("");
        getTfobservacoes().setText("");
        
    }//GEN-LAST:event_btnenviarActionPerformed

    private void tfobservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfobservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfobservacoesActionPerformed

    private void tfvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfvalorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CocaCola;
    private javax.swing.JSpinner Fanta;
    private javax.swing.JSpinner Guarana;
    private javax.swing.JButton btnenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner selecaoBA;
    private javax.swing.JSpinner selecaoBF;
    private javax.swing.JSpinner selecaoBP;
    private javax.swing.JSpinner selecaoCDS;
    private javax.swing.JSpinner selecaoCMB;
    private javax.swing.JSpinner selecaoCP;
    private javax.swing.JSpinner selecaoFG;
    private javax.swing.JSpinner selecaoP;
    private javax.swing.JSpinner selecaoPF;
    private javax.swing.JTextField tfobservacoes;
    private javax.swing.JTextField tfvalor;
    // End of variables declaration//GEN-END:variables

    public JSpinner getCocaCola() {
        return CocaCola;
    }

    public void setCocaCola(JSpinner CocaCola) {
        this.CocaCola = CocaCola;
    }

    public JSpinner getFanta() {
        return Fanta;
    }

    public void setFanta(JSpinner Fanta) {
        this.Fanta = Fanta;
    }

    public JSpinner getGuarana() {
        return Guarana;
    }

    public void setGuarana(JSpinner Guarana) {
        this.Guarana = Guarana;
    }

    public JSpinner getSelecaoBA() {
        return selecaoBA;
    }

    public void setSelecaoBA(JSpinner selecaoBA) {
        this.selecaoBA = selecaoBA;
    }

    public JSpinner getSelecaoBF() {
        return selecaoBF;
    }

    public void setSelecaoBF(JSpinner selecaoBF) {
        this.selecaoBF = selecaoBF;
    }

    public JSpinner getSelecaoBP() {
        return selecaoBP;
    }

    public void setSelecaoBP(JSpinner selecaoBP) {
        this.selecaoBP = selecaoBP;
    }

    public JSpinner getSelecaoCDS() {
        return selecaoCDS;
    }

    public void setSelecaoCDS(JSpinner selecaoCDS) {
        this.selecaoCDS = selecaoCDS;
    }

    public JSpinner getSelecaoCP() {
        return selecaoCP;
    }

    public void setSelecaoCP(JSpinner selecaoCP) {
        this.selecaoCP = selecaoCP;
    }

    public JSpinner getSelecaoFG() {
        return selecaoFG;
    }

    public void setSelecaoFG(JSpinner selecaoFG) {
        this.selecaoFG = selecaoFG;
    }

    public JSpinner getSelecaoP() {
        return selecaoP;
    }

    public void setSelecaoP(JSpinner selecaoP) {
        this.selecaoP = selecaoP;
    }

    public JSpinner getSelecaoPF() {
        return selecaoPF;
    }

    public void setSelecaoPF(JSpinner selecaoPF) {
        this.selecaoPF = selecaoPF;
    }

    public JSpinner getSelecaoCMB() {
        return selecaoCMB;
    }

    public void setSelecaoCMB(JSpinner selecaoCMB) {
        this.selecaoCMB = selecaoCMB;
    }

    public JTextField getTfobservacoes() {
        return tfobservacoes;
    }

    public void setTfobservacoes(JTextField tfobservacoes) {
        this.tfobservacoes = tfobservacoes;
    }

    public JTextField getTfvalor() {
        return tfvalor;
    }

    public void setTfvalor(JTextField tfvalor) {
        this.tfvalor = tfvalor;
    }


       

}
